name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install PyTorch separately first, as it's a core dependency for fmm_torch
        # Using a version compatible with a wide range of Python versions for CI
        python -m pip install torch --index-url https://download.pytorch.org/whl/cpu
        # Install project with dev dependencies (includes pytest, ruff, mypy, pydocstyle)
        python -m pip install .[dev]

    - name: Check formatting with Ruff
      run: ruff format --check .

    - name: Lint with Ruff
      run: ruff check .

    - name: Type check with MyPy
      run: mypy src

    - name: Check docstrings with Pydocstyle
      run: pydocstyle src

    - name: Run tests with Pytest
      run: |
        PYTHONPATH=src pytest tests

    # Placeholder for tests until actual tests are added
    # - name: Test with Pytest
    #   run: pytest
